version: "3.9"
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.3.5
    volumes:
      - ~/.aws:/root/.aws
      - ./:/tf
    working_dir: /tf/infra/dev
    environment:
      env: "dev"